language: ruby
rvm:
  - 2.4.1

before_install: 
  - gem install bundler
  - bundler update --bundler

install: gem install jekyll html-proofer
script: jekyll build && htmlproofer ./_site --url-ignore "/gz-bigindex/*/"

# branch whitelist, only for GitHub Pages
branches:
  only:
  - review_docs
  - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false